services:
  backend:
    build: ./backend
    container_name: bcs10nakul-fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend
    container_name: bcs10nakul-react-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: always